### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Render#1]
How would you make transitions/animations between states?

**Comment by alexdrone** [comment]
Hello :)
Run `renderComponent()` inside of an animation block to to witness the magic.

``` swift
self.myComponentState.expanded = !self.myComponentState.expanded 
self.component.state = self.myComponentState
UIView.animateWithDuration(0.3) {
    self.component.renderComponent()
}
```

![animation](https://cloud.githubusercontent.com/assets/238849/15267811/b1615524-19cc-11e6-83e7-1c987ea20027.gif)

**Comment by zdnk** [comment]
this works nice for size and position changes, what i was thinking of is hiding/showing children

**Comment by alexdrone** [comment]
So currently there's a default transition for views coming in and out from the view hierarchy and that's a simple fade-in.
I will work on extending the component interface so that these animations can be configured.

**Comment by zdnk** [comment]
Awesome, I havnt got a chance to get hands-on with Render yet, but so far it looks really good.
I have some doubts about performance with more complex screens, maybe it would be worth to do some of the stuff in background threads, if it is possible.
