### ISSUE TITLE
JSON Serialization

### ISSUE THREAD

**Issue by kantorcodes** [alexdrone/Render#10]
Hey Alex!

Lovely library you made here. I saw you were looking to add json deserialization from files or json? 

My library https://github.com/OatmealCode/Oatmeal has that built in. You could read components from files/apis/cache and convert them back into objects! Let me know if you decide to give it a whirl, and feel free to reach out!

**Comment by alexdrone** [comment]
I'll absolutely check out your lib :) 👍
