### ISSUE TITLE
What happened to ComponentCollectionViewCell?

### ISSUE THREAD

**Issue by chetem** [alexdrone/Render#101]
I'm wanting to create a `UICollectionView` in the more traditional way by using `ComponentCollectionViewCell`. The documentation and previous versions of Render had that class available, but in the latest version I'm using (`4.9.2`) it seems to be missing. `ComponentTableViewCell` is still there, just not the `ComponentCollectionViewCell`. Am I missing something?

While I'm at it, the main reason for me wanting to use the older way is to allow for moving around of items through drag and drop. I couldn't figure out a way using the `CollectionNode`, but if it's possible and recommended to use `CollectionNode` instead I'm all for it! Please let me know how :).

Thanks for the help!

**Comment by alexdrone** [comment]
I'm porting the collection view wrapper to neutrino (5.0)
