### ISSUE TITLE
Updating a panning view fails to 

### ISSUE THREAD

**Issue by AndrewLipscomb** [alexdrone/Render#105]
I'm not sure if this would be a bug or simply the by-product of the way Render functions.

I'm making a small bar which sits at the RHS side of a screen, and can be dragged left-right to expand its size. The issue I've seen with this is that during an update, Render disconnects and recreates the GestureHandler which deals with this panning. 

I would hope that there would be a combination of flags (or potentially some modifications to the source) which would allow this view to perform its layouts, but not recreate the GestureHandlers/callbacks. Any clues on whether this is achievable? Or could be modded in with some edits on my end? 

A snippet of the code below.

```
struct ExpandingViewState: StateType {
    var dragWidth: CGFloat = 200
}

class ExpandingView : ComponentView<ExpandingViewState>  {
    
    required init() {
        super.init()
        defaultOptions = [.preventViewHierarchyDiff]
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func onHandlePan(gestsureRecogniser: UIGestureRecognizer) {
        if (gestsureRecogniser.numberOfTouches > 0) {
            let point = gestsureRecogniser.location(ofTouch: 0, in: self.rootView)
            let newWidth = UIScreen.main.bounds.width - point.x
            self.setState{ state in
                state.dragWidth = newWidth
            }
        }
    }
    
    override func render() -> NodeType {
        return Node<UIView>(
            reuseIdentifier: "ExpandingView_root",
            key: "ExpandingView_root",
            props: { view, layout, size in
                view.backgroundColor = UIColor.red
                layout.width = self.width
                layout.percent.height = 100%
                layout.right = 0
                layout.position = .absolute
                layout.flexDirection = .row
            }
        ).add(children: [
            Node<UIView>(
                reuseIdentifier: "ExpandingView_handle",
                key: "ExpandingView_handle",
                props: { view, layout, size in
                    view.onPan(self.onHandlePan)
                    view.backgroundColor = UIColor.blue
                    layout.width = 10
                    layout.percent.height = 100%
            }),
            Node<UIButton>(
                reuseIdentifier: "ExpandingView_button",
                key: "ExpandingView_button",
                props: { view, layout, size in
                    view.backgroundColor = UIColor.red
                    view.setTitle("Button", for: .normal)
                    view.setTitleColor(UIColor.blue, for: .normal)
                    view.setTitleColor(UIColor.blue, for: .highlighted)
                    layout.flexGrow = 1
                    layout.percent.height = 100%
            })
        ])
    }
}
```

**Comment by AndrewLipscomb** [comment]
Forgot to mention - this is not Neutrino, this is the Classic build. 

Think I may have figured out a hack for myself - I've added in an early return inside of onGestureRecognizer<T> with an optional flag to set up once and never modify. This could probably be optimised to do some equivalence checking so that a purely layout related props update does not break gesture recognition. 

That said - Neutrino is your focus, if you'd like I can make a QoL pull for the older one.

**Comment by alexdrone** [comment]
Have you considered moving to Neutrino?

**Comment by AndrewLipscomb** [comment]
We have used the older version and will probably update at some point in the next few months. As of now we have made a few mods to the framework as we need as QoL improvements - but with no real testing beyond our usage. 

Does Neutrino handle this part of the API more granularly?

**Comment by AndrewLipscomb** [comment]
BTW we are personally not using the render 4 lib anymore - these older issues can probably be closed if you see no more value in them.
