### ISSUE TITLE
Cocoapods please

### ISSUE THREAD

**Issue by lfarah** [alexdrone/Render#11]
I'd be cool to also add Cocoapods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by alexdrone** [comment]
Thank you for your feedback! I will work on adding cocoa pods support hopefully today!

**Comment by alexdrone** [comment]
Done. :) It should be working now.

**Comment by lfarah** [comment]
Awesome. Good job!

**Comment by ysyyork** [comment]
Could you also add pod support to README? Thanks 👍
