### ISSUE TITLE
AppKit Support?

### ISSUE THREAD

**Issue by connorwyatt** [alexdrone/Render#110]
Hey, I was wondering if you have any plans to support AppKit with Render?

**Comment by alexdrone** [comment]
I think we'll just be waiting for marzipan for macOS support!

**Comment by ngocdaothanh** [comment]
Hi, I really want to use Render in a Mac app.
Will AppKit be supported very soon?

> waiting for marzipan

Do you mean this user has a fork to support AppKit?
I don't see anything:
https://github.com/Marzipan?tab=repositories

**Comment by ngocdaothanh** [comment]
OK, I see that this is marzipan:
https://techbeacon.com/app-dev-testing/ios-apps-macos-what-marzipan-means-dev-teams
