### ISSUE TITLE
Use of _kvcKeyPathString for the identifier in AnyKeyPath extension

### ISSUE THREAD

**Issue by AndrewLipscomb** [alexdrone/Render#112]
More a question/feedback than a legit bug 

The extension for getting the identifier is less than optimal because:
- It forces the use of the `@objc` preface for any overrides/subclasses of standard UIView classes which have added properties you'd wish to manipulate via the main `spec.set` pattern.
- This may not be possible for some properties, a good example being the `UIEdgeInsets` struct, as Swift structs cannot be `@objc`ified. 

The old `hashValue` method seemed to work without (obvious) issues before - would there be a reason to not do the following

```
  public var identifier: String {
    guard let path = _kvcKeyPathString else {
    // Structs and non objc marked properties end up here
     return String(hashValue)
    }
    return path
  }
```

**Comment by alexdrone** [comment]
Yes, that would def work.
I'm just concerned about hashValue collisions.
I reverted that previously because it was broken in iOS 10 beta.
Do you wish to make a pull request about it?

**Comment by AndrewLipscomb** [comment]
Pull [here](https://github.com/alexdrone/Render/pull/113)

I wasn't able to get the tests to run on my machine ("The bundle identifier of the application could not be determined.", fiddling with the PList value of the Test target didn't help). 

Whats the worst case scenario with a hashValue collision? Would potentially a wrongly typed value be cast badly into a property? 

Our prime example for wanting this is the Google Maps lib, which has its own classes we need to wrap for use in Render and makes use of `UIEdgeInsets`. That said if the risk of collisions is significant and the failure when collisions are met is bad then maybe a better solution would be good.
