### ISSUE TITLE
Questions about `prune(view)`

### ISSUE THREAD

**Issue by hfossli** [alexdrone/Render#14]
Hey. Nice work! 

I have not used your framework yet. I've only read the source as I have another closed source project (closed for now) in objc which also takes great inspiration from react. 

About this method:
https://github.com/alexdrone/Render/blob/a6c7086d24d46dd651634fd6e170653604e4430f/Render/ComponentView.swift#L71-L79

A UIScrollView has two UIImageView's as subviews – the scroll indicators. There are many types of views which uses subviews internally. UIButton, UITableView, etc etc. Do you take that into account when reusing views? 

In my framework I'm thinking that I might need to have separate rules for reusing and splitting up the different types of views depending on its structure.

**Comment by alexdrone** [comment]
The diff algorithm works with the componentNodes and not with the views.. So the granularity is different. Every node has a view associated (and that can be a complex view hierarchy per se) - the infra won't be touching views that are subviews of the node root view.

**Comment by hfossli** [comment]
I see. Clever 👌🏼
