### ISSUE TITLE
Corner radius & shadow

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Render#17]
How do I setup corner radius if I want shadow at the same time?

```
public class NavigationCommandView: ComponentView {


    public override func construct() -> ComponentNodeType {
        layer.shadowRadius = 3
        layer.shadowOffset = CGSize(width: 0, height: 0)
        layer.shadowColor = UIColor.blackColor().CGColor
        layer.shadowOpacity = 0.6

        return ComponentNode<UIView>().configure({ (view: UIView) -> Void in
            ....
        })
    }

    override public func layoutSubviews() {
        super.layoutSubviews()

        layer.cornerRadius = bounds.size.height / 2
        layer.masksToBounds = true
    }

}
```

This wont work because maskToBounds makes shadow invisible because of the mask. And I cannot set conernerRadius to CoMponentNodes view because I dont know its size just yet.

**Comment by alexdrone** [comment]
Just assign those properties (shadowRadius and such) inside the configuration closure.

**Comment by alexdrone** [comment]
let me know if it works! :)

**Comment by zdnk** [comment]
I cannot because I dont know the size of the view so i cannot do `bounds.size.height / 2` calc. The size is calculated based on children. At the time of configuration would occur, `size` would be `(0, 0)`.

**Comment by wokalski** [comment]
It looks like something like `react-native`'s `onLayout` is needed.

**Comment by alexdrone** [comment]
Will add the onLayout callback soon!
