### ISSUE TITLE
Replace own implementation of FlexBox with SwiftBox

### ISSUE THREAD

**Issue by wokalski** [alexdrone/Render#22]
Cool project! Not using it but wanted to suggest to replace your own implementation of FlexBox with [SwiftBox](https://github.com/joshaber/SwiftBox). Sorry if you've considered it and it doesn't make sense. It's always good to have less code to maintain.

**Comment by alexdrone** [comment]
Swiftbox unfortunately is stuck with an old version of flexbox.
