### ISSUE TITLE
The "flex" style property vs. flex-grow and flex-shrink

### ISSUE THREAD

**Issue by gmckenzi** [alexdrone/Render#24]
I'm familiar with the FlexBox model (at least I think I am), but I don't understand how the "flex" property works in this implementation given that there doesn't appear to be a corresponding property in CSS.

In the FlexBoxLayout project that Render incorporates (https://github.com/alexdrone/FlexboxLayout) there is an example which shows two components expressing "flex" property values of 0.8 and 0.2 respectively. I assume this means that the first component wants to take 80% of the available space and the other component 20% of the space? Is that what it means? If so, does the flex property have priority over the other properties?

Lastly, is there any plans to support flex-grow and flex-shrink?

**Comment by alexdrone** [comment]
Fixed by integrating the latest css-layout.
