### ISSUE TITLE
Render build fails for "Generic iOS Device" configuration

### ISSUE THREAD

**Issue by gmckenzi** [alexdrone/Render#29]
Using Xcode Version 8.1 (8B62). Opened either the Render or RenderTodoDemo projects attempt to build for "Generic iOS Device", and the build fails at BaseComponentView.swift#69 "`Type 'KeyCommands' has no member 'register'`".

Possibly this is caused by how the `#if (arch(i386) || arch(x86_64)) && (os(iOS) || os(tvOS))` is getting evaluated in KeyCommands.swift ?

**Comment by alexdrone** [comment]
Fixed 👍
