### ISSUE TITLE
Different behaviour for setting margin with CSSEdgeAll vs. individual left/top/right/bottom

### ISSUE THREAD

**Issue by gmckenzi** [alexdrone/Render#30]
I'm observing that when I `css_setMargin(value, for:CSSEdgeAll)` the margin values do not appear to take effect, whereas when I set individual left/top/right/bottom margins with individual `css_setMargin()` calls, the margins work properly.

I expect this is likely an issue with the Facebook library, but I wanted to report it in case I misunderstood how to use CSSEdgeAll and/or if you had encountered this issue.

**Comment by alexdrone** [comment]
I checked and unfortunately seems to be an issue in css-layout.
I currently worked around this by overriding css_setMargin and manually adding  left/top/right/bottom margin when All is passed as argument.
