### ISSUE TITLE
UIScrollview postRender

### ISSUE THREAD

**Issue by gmckenzi** [alexdrone/Render#31]
I have a tree of component views that are added to a UIScrollView at runtime.
I see that there are postRender methods in extensions (i.e. Reset.swift) that look like they are designed to automatically resize a scroll view to properly host the rendered layout. However, it isn't clear to me how to take advantage of this. I currently manually call the intrinsicSize method after rendering to determine the layout size and adjust my scroll view, but this is inefficient because calling intrinsicSize causes a separate rendering of the tree to occur.

I can see that the postRender method of the extension is never invoked. What do I need to do to get my scroll views to automatically adjust? Rather than adding my root component view as a subview of my scroll view, should I be constructing the scroll view itself as a component view?

**Comment by gmckenzi** [comment]
Upon closer review of RenderToDoDemo, I see that it instantiates a UIScrollView as a component. I'm assuming this is best practice?

**Comment by alexdrone** [comment]
Yes, the scrollview should be a component node as well in order to have postRender called on it.
