### ISSUE TITLE
[Bug] Emptying a node's children causes it to incorrectly measure its size

### ISSUE THREAD

**Issue by esam091** [alexdrone/Render#36]
### Code
```Swift
import PlaygroundSupport

import Render

PlaygroundPage.current.needsIndefiniteExecution = true

struct AppState: StateType {
    var isOn = true
}

class MyView: ComponentView<AppState> {
    override func construct(state: AppState?, size: CGSize) -> NodeType {
        
        let makeChild = {
            return Node<UILabel>() { label, _, _ in
                label.text = "title"
            }
        }
        
        let children = [
            makeChild(),
            makeChild(),
            makeChild(),
            makeChild()
        ]
        
        return Node().add(children: [
            Node() { view, layout, size in
                view.backgroundColor = .blue
                layout.height = 50
            },
            Node().add(children: state!.isOn ? children : []),
            Node() { view, layout, size in
                view.backgroundColor = .green
                layout.height = 50
            }
        ])
    }
}

let container = UIView(frame: CGRect(x: 0, y: 0, width: 320, height: 568))
container.backgroundColor = .white

let view = MyView()
view.state = AppState()
view.render(in: container.frame.size)

container.addSubview(view)

view.state?.isOn = !view.state!.isOn
view.render(in: container.frame.size)

PlaygroundPage.current.liveView = container
```

### Expected:
<img width="321" alt="screen shot 2017-03-18 at 12 04 46" src="https://cloud.githubusercontent.com/assets/3784411/24069207/096134d8-0bd5-11e7-8454-dffaf8cf9dff.png">

### Actual:
<img width="320" alt="screen shot 2017-03-18 at 12 05 21" src="https://cloud.githubusercontent.com/assets/3784411/24069215/187cd396-0bd5-11e7-9790-bed82bed8778.png">

This happens because when the container is empty, it becomes a leaf node, and leaf nodes are measured [by](https://github.com/alexdrone/Render/blob/1eaa824de2483992a6c66d26f630f2905a2513f2/Render/objc/YGLayout.m#L133) [using `sizeThatFits:`](https://github.com/alexdrone/Render/blob/1eaa824de2483992a6c66d26f630f2905a2513f2/Render/objc/YGLayout.m#L278-L280). UIView's implementation only reports [its current size](https://developer.apple.com/reference/uikit/uiview/1622625-sizethatfits).

One solution that I've tried is by setting view's size to zero before marking dirty and it works.

**Comment by alexdrone** [comment]
could you make a PR for it?

**Comment by esam091** [comment]
Done, please take a look #37 🙂

**Comment by alexdrone** [comment]
Great work! 🥇
