### ISSUE TITLE
[Question] Styling

### ISSUE THREAD

**Issue by garsdle** [alexdrone/Render#41]
Hey first of all I love what you have made here, really impressive! 🍻 

My question: Does anyone have any suggestions for styling an app that uses Render. Specifically styling across multiple components? Either some css (I wish...) like 3d party library you may be using or maybe just how you custom do it to live in harmony with your designer. I've taken a look at StyleKit and NUI but am not sure I'm convinced by either.

I really appreciate any wisdom.

Cheers!
Manny

**Comment by alexdrone** [comment]
First of all, thank you! :)

Check out alexdrone/S - it generates code from a Yaml stylesheet (I prefer the speed and deterministic nature of generated code).
