### ISSUE TITLE
Wrapper of ComponentView in a UICollectionViewCell did not wrap correctly 

### ISSUE THREAD

**Issue by doraeminemon** [alexdrone/Render#42]
ComponentCollectionViewCell did not replicate the state to the ComponentViewType. 
Here's the code for ComponentTableViewCell 
```swift open class ComponentTableViewCell<C : ComponentViewType>: UITableViewCell {

  public var state: C.StateType? {
    didSet {
      self.componentView?.state = state
    }
  }
```
while the same part of code in ComponentCollectionViewCell is missing it 
```swift
open class ComponentCollectionViewCell<C : ComponentViewType>: UICollectionViewCell {

  public var state: C.StateType? // did not set the state of the wrapper to the actual ComponentView
```

This is a trivial fix, so I hope it's being fixed soon without need to do a pull request. Thanks

**Comment by alexdrone** [comment]
Thank you for the report!
I've fixed the issue and I'm pushing a new release to cocoapods (2.5.1) 👍
