### ISSUE TITLE
Can't import framework after CocoaPods install

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#44]
Setup a fresh iOS Swift Xcode project and then added the framework using CocoaPods. It says it installed successfully, but then when I try to import the framework in my class, I get nothing. It says there's no such module. I simply followed standard procedure with the install, but nothing. Something seem broken.

1. have latest cocoapods-1.2.1 installed on my system.
2. Created a single view iOS app
3. added  pod 'Render', '~> 2.7' to my pod file in my app target.
4. use_frameworks! is there.
5. tried to import Render in my ViewController class.

Am I going to have to add the framework manually?

**Comment by alexdrone** [comment]
Do you use use_frameworks! by any chance?

**Comment by jewilhel** [comment]
Yes I did. Is that the problem?

**Comment by alexdrone** [comment]
Unfortunately I can't reproduce this issue.
I just tried with a clean slate project and everything seems to be working properly.
Try to install another pod and let me know if you have the same issue.
