### ISSUE TITLE
How to return ComponentView from a function?

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#50]
Is there a way to return a selected instance of componentView from a function without having to recast it later into a concrete types such as `ComponentView<BackgroundState>`?
Using `AnyComponentView` as shown doesn't seem to work the way I hoped. 

```swift
    func makeComponent(select: Int) -> AnyComponentView  {
        switch select {
            case 1:
            return BackgroundComponent()
            case 2:
            return CardComponent()
            case 3:
            return ImageComponent()
            case 4:
            return TitleBarComponent()
        default:
            return DefaultComponent()
        }
    }
```

I want to dynamically construct a view hierarchy in my viewController.

**Comment by alexdrone** [comment]
AnyComponentView now has all of the APIs exposed :)

**Comment by jewilhel** [comment]
That's great! Thanks so much for the update! :)
