### ISSUE TITLE
Need Collection View Examples

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#52]
Would like to see an example of a collection view as a component in one of the demos or in the documentation. Tried to implement one but got stuck. (See my code in issue #39 )
Wish it was as easy to implement as TableNode.

Thanks for the great framework Alex! I'm liking it more and more! 👍 

Jason W.

**Comment by alexdrone** [comment]
I'm working on *CollectionNode* - a collection view wrapper with the exact same API of *TableNode* - so stay tuned 👍

**Comment by alexdrone** [comment]
Render 4.1 is out and introduces CollectionNode.
The API is the same for TableNode - let me know if you find any issues!!

**Comment by jewilhel** [comment]
Wow! That's amazing! Thanks!!!!
I will go and try it out right away.
