### ISSUE TITLE
TableNode and CollectionNode stop working when nested inside of a parent node

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#55]
I'm trying to nest a `TableNode` or `CollectionNode` inside a parent node like this:

```swift
return parent.add(children: [collection.add(children: cells)])
```

But then the child cells stop rendering as if the datasource is inactive.

Indeed, when I setup a manual implementation of `UICollectionView` and nest it inside of a parent node as above, its datasource methods aren't called at all. Perhaps, this has something to do with `ComponentTableViewCell` and `ComponentCollectionViewCell`.

Would appreciate any insight you might have!
thanks, Jason W.

**Comment by alexdrone** [comment]
Can you provide a sample code I could use to debug the issue?
I tried to wrap a TableNode inside another and I don't see issues so far.

**Comment by jewilhel** [comment]
Here is the test component I built:
```swift
import Foundation
import UIKit
import Render

class CollectionContainer: ComponentView<NilState> {
    required init() {
        super.init()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("Not supported")
    }
    
    override func render() -> NodeType {
        
        let parent = Node<UIView>(key: "green") { (view, layout, size) in
                layout.width = size.width
                layout.height = size.height
                view.backgroundColor = UIColor.gray
        }
        
        let collection = CollectionNode(parent: self) { (view, layout, size) in
            view.backgroundColor = UIColor.darkGray
            layout.width = size.width
            layout.height = size.height
        }
        
        let cells = [
            Node<UIView>(key: "green") { (view, layout, size) in
                layout.width = 70
                layout.height = 70
                view.backgroundColor = UIColor.green
            },
            
            Node<UIView>(key: "red") { (view, layout, size) in
                layout.width = 70
                layout.height = 70
                view.backgroundColor = UIColor.red
            },

            Node<UIView>(key: "blue") { (view, layout, size) in
                layout.width = 70
                layout.height = 70
                view.backgroundColor = UIColor.blue
            }
        ]
        //return collection.add(children: cells)  //This works fine
        return parent.add(children: [collection.add(children: cells)]) //This one fails
    }
}
```
The cells above disappear when the collection node is placed inside the parent node. 
I'm using a super simple viewController nothing interesting going on there:

```swift
import UIKit
import ReSwift
import Render

class ViewController: UIViewController, StoreSubscriber, ComponentController {
    typealias StoreSubscriberStateType = AppState
    
    var component = CollectionContainer()
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
   }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        mainStore.subscribe(self)

        componentControllerViewDidLoad()
    }
    
    func newState(state: AppState) {
      //No-Op
    }
}
```
Using Render framework with ReSwift as you can tell.

**Comment by jewilhel** [comment]
I just tried your **"Preliminary fix for lists wrapped inside nodes"** and it seemed to work for me even in its preliminary form. 

Thanks for your help on this, it really helps me move forward in my project! :)

**Comment by jewilhel** [comment]
I went back and tested a manual implementation of `UICollectionView` node using `ComponentCollectionViewCell` but it still fails to render `cells` when nested in a parent node.

**Comment by alexdrone** [comment]
I fixed several other issues on the collection view - I'm focusing on this one right now 👍 
I'm able to reproduce it - should be able to fix it fairly soon.

**Comment by alexdrone** [comment]
Render 4.2 is out and fixes that issue 👍  :)
