### ISSUE TITLE
CollectionNode not displaying all of its cells until scrolled off screen and back again

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#56]
I created an array of card components and configured and rendered them externally, then passed them into my Collection component as nodes where they are added as children to `CollectionNode`. When I run the app I have 8 cards in the `elements` array, but only 1 card will display on screen, which is unexpected. If I swipe up and cause the view to scroll upwards so that the non displaying cards move off screen and then back on again, the other cards appear where they are supposed to be.

I'm guessing the cards reentering the screen cause them to refresh/render whereas they initially did not. I looked for a way to update CollectionNode, but nothing I tried made a difference.

Here is my code if it helps:

```swift
import Foundation
import UIKit
import Render

struct CollectionState: StateType {
    var id: String = "collectionContainer"
    var elements: [NodeType] = [layoutBuilder("")]
    var layoutAs: String = "flow"
}

class CollectionContainer: ComponentView<CollectionState> {
    required init() {
        super.init()
        self.state = CollectionState()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("Not supported")
    }
    
    override func render() -> NodeType {
        
        let collection = CollectionNode(key: self.state.id, parent: self, create: {
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: self.setFlowLayout())
            collectionView.showsHorizontalScrollIndicator = false
            collectionView.showsVerticalScrollIndicator = false
            collectionView.clipsToBounds = false
            collectionView.backgroundColor = UIColor.clear
            collectionView.reloadData()
            return collectionView
            
        }) { (view, layout, size) in
            layout.percent.width = 100%
            layout.percent.height = 100%
            configs[self.state.layoutAs]!(layout)
        }
        return collection.add(children: self.state.elements)
    }
    
    func setFlowLayout() -> UICollectionViewLayout {
        let layout = UICollectionViewFlowLayout()
        layout.sectionInset = UIEdgeInsetsMake(30, 10, 10, 10)
        layout.minimumInteritemSpacing = 10
        layout.minimumLineSpacing = 15
        return layout
    }
}
```
You'll notice I'm customizing the collectionView, `CollectionNode` is using with the `create:` closure so I can control the layout and set other properties, however not everything works as expected.

I tried to get access to the cell's view so that I could set `clipsToBounds` to False, since it clips the shadows off my cards, but I'm not sure how to properly customize `cells` using `CollectionNode`.
As always your help is so appreciated! :)

**Comment by alexdrone** [comment]
I haven't played around with other layouts (I forked a custom layout from IGListKit because it works better than the traditional flow layout).
PS: You can achieve margins and line spacing by introducing padding in the component view as well.

**Comment by jewilhel** [comment]
I can't figure out how to add margins and line spacing by introducing padding as you described above. The layout of the `CollectionNode` and `Cells` is not intuitive like the rest of the framework. I think the cells should set `clipsToBounds = false` because my nodes are getting clipped inside the cells.

**Comment by alexdrone** [comment]
You can achieve margins by having a transparent wrapper view in the card component with some padding.

In general the case of custom layouts for collection view is not supported for CollectionNode, but you can always use your collectionView traditionally in a VC and wrap your component in CompontentCollectionViewCells.

**Comment by jewilhel** [comment]
Thanks for your work on this and your suggestions Alex. My cards already have a wrapper on them and I did something similar to your suggestions, but this won't work for my long term needs.

I did create a traditional `collectionView` and wrap my card components in `ComponentCollectionCell` as you suggested above, but when I went to nest the component containing the collectionView inside of another component the datasource stopped working just like the `CollectionNode` did before your changes. I'm not able to implement the collectionView directly in the `ViewController` because I'm building a hierarchy of nested components one of which is a `CollectionView`. My code looks like this:

```swift
import Foundation
import UIKit
import Render

struct OldCollectionState: StateType {
    var id: String = "collectionContainer"
    var elements: [NodeType] = [layoutBuilder("")]
    var layoutAs: String = "flow"
    var direction: String = "vertical"
}

class OldCollectionContainer: ComponentView<OldCollectionState>, UICollectionViewDataSource, UICollectionViewDelegate {
    
    var collectionView: UICollectionView?
    
    required init() {
        super.init()
        self.state = OldCollectionState()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("Not supported")
    }
    
    override func render() -> NodeType {
        if let collection = self.collectionView {
            print(collection)
        }
        // A container view that wraps it's contents
        func layoutContainer() -> NodeType {
            return Node<UICollectionView>(key: state.id,
                create: {
                    let collectionView = UICollectionView(frame: .zero, collectionViewLayout: self.setFlowLayout())
                    collectionView.register(ComponentCollectionViewCell.self, forCellWithReuseIdentifier: CellComponent.reuseIdentifier)
                    collectionView.dataSource = self
                    collectionView.delegate = self
                    collectionView.backgroundColor = UIColor.clear
                    collectionView.isPagingEnabled = true
                    collectionView.showsHorizontalScrollIndicator = false
                    collectionView.showsVerticalScrollIndicator = false
                    collectionView.alwaysBounceHorizontal = true
                    collectionView.clipsToBounds = false
                    collectionView.allowsSelection = true
                    self.collectionView = collectionView
                    return collectionView
                },
                configure: {(collection,layout,size) in
                    layout.width = size.width
                    layout.height = size.height
                    configs[self.state.layoutAs]!(layout)
                    configs[self.state.direction]!(layout)
            }
            )}
        
        return layoutContainer()
    }
    
    // tell the collection view how many cells to make
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
    return state.elements.count
    }
    
    // make a cell for each cell index path
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let id = CellComponent.reuseIdentifier
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: id, for: indexPath)
        
        if let cell = cell as? ComponentCollectionViewCell {
            cell.mountComponentIfNecessary(CellComponent())
            cell.clipsToBounds = false
            cell.set(state: CellState(node: self.state.elements[indexPath.row]))
            print("Add Cells")
            cell.update()
        }
        return cell
    }
    
    // Customize collection layout
    func setFlowLayout() -> UICollectionViewLayout {
        let layout = UICollectionViewFlowLayout()
        layout.estimatedItemSize = mainStore.state.componentSize
        layout.sectionInset = UIEdgeInsetsMake(30, 10, 10, 10)
        layout.minimumInteritemSpacing = 10
        layout.minimumLineSpacing = 15
        return layout
    }
}
```

**Comment by alexdrone** [comment]
The code looks right! I will have a look at it right away.
Thank you for the feedback!

**Comment by jewilhel** [comment]
Thanks so much! I really appreciate all your support! :)

**Comment by jewilhel** [comment]
I will also provide example code on this one.

**Comment by alexdrone** [comment]
I finally get to work on this issue - Making some progress, hopefully I'll get it to work by the end of today :)

**Comment by jewilhel** [comment]
I can provide sample code if you need it

**Comment by jewilhel** [comment]
YES!!! The issue seems to be fixed now. My `CollectionNode` is working and displays all the child cells/nodes correctly.

Thanks so much for working on this! :)

**Comment by jewilhel** [comment]
I still wish the cells didn't clip their content. It messes up the shadows of my cards. The only way for me to work around this is to add extra padding to my cards which throws off my size calculations for the cards. Anyway, not a deal breaker but would be nice.

**Comment by jewilhel** [comment]
The cell clipping also affects the layer animations that I applied to my cards. I really need a way to disable clipping on each cell in my collection, like this:

`cell.clipsToBounds = false`
