### ISSUE TITLE
Documentation for new features

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Render#59]
It seems like there are new features introduced like animations, console, inspector, TableNode, CollectionNode etc., but documentation is still very basic. Like what is the proper use of reuseIdentifier and key? How to properly use TableNode with diff updates, how to use console and inspector?

**Comment by jewilhel** [comment]
I have to agree with this post. I'm finding it difficult to deploy the new CollectionNode. I've tried to piece together code from the demo app and reading the comments in the framework code, but I can't seem to get a working CollectionNode working without all sorts of problems and I don't know if its something in my code or bugs that still persist in the framework.

The console and inspector sound interesting and want to learn about them too.

**Comment by alexdrone** [comment]
I'm finishing up some of the new features and revamping doc and samples -
my goal is to make a big new release (5.0) very soon with mostly just more
tooling, docs, samples and no api changes.

The console/inspector is something very similar to the chrome dev tools -
we'll be able to inspect props and state of every node remotely.

Unfortunately writing the documentation takes a long time and it's
something I'm prioritizing right now.

Thank you for your extremely useful feedback and for supporting the project
:)

ps: I plan to publish some items that are good candidate for contribution :)

**Comment by jewilhel** [comment]
Thanks for all the great new examples Alex, I'll be spending some time reviewing them so I can improve my code quality and maximize my usage of this terrific framework. 👍

**Comment by alexdrone** [comment]
Thank you :) 
I working on a big re-write of the documentation as well.
In general the principles and the API of the framework are as close as possible to React - so a lot of the documentation out there about best principles and such applies to Render as well.

for example: https://github.com/uberVU/react-guide/blob/master/props-vs-state.md
