### ISSUE TITLE
TableNode with diff error

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Render#62]
Hey,
I have issue with `TableNode` again. This is the setup:
```swift
    override func render() -> NodeType {
        let table = TableNode(
            reuseIdentifier: "list-table",
            key: "list-table",
            in: self,
            cellReuseEnabled: true,
            autoDiffEnabled: false
        ) { view, layout, size in
            layout.width = size.width
            layout.height = size.height
            
            view.backgroundColor = .clear
        }
        
        let nodes = state.approvals.map { item -> NodeType? in
            do {
                return try self.nodeFactory.create(for: item, in: self)
            } catch let error {
                print(error)
                return nil
            }
        }.flatMap { $0 } // remove nils from array
        
        table.add(children: nodes)
        
        return table
    }
```
This is also what `nodeFactory.create(for:, in:)` does:
```swift
        let state = GenericApprovalsListItemState(
            id: entity.id,
            title: entity.headline,
            subtitle: entity.subheadline,
            iconName: entity.iconName,
            currency: nil,
            amount: nil,
            itemDescription: entity.itemDescription,
            note: entity.note,
            escalation: .none,
            attachments: nil
        )
        
        let component = GenericApprovalsListItemComponentView()
        
        return ComponentNode(
            component,
            in: parent,
            key: "list-item-midas-\(entity.id)",
            state: state
        )
```
I am just pushing a new state with updated array of items and adding the children. Every time all of them again - I hope that is right.
It ends up with:
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (18) must be equal to the number of rows contained in that section before the update (0), plus or minus the number of rows inserted or deleted from that section (6 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
```

Also setting up the `contentInset` does not seem to work.

Also is there a recommended way how to add UIRefreshControl?

**Comment by zdnk** [comment]
I added some printing and this is the result. For some reason it computes that the first item should be removed and then readded. But I guess it still does not explain why it crashes.

> #diff old: ["list-item-midas-midas_1b0157b280d8082b", "list-item-midas-midas_1b0157b280cda4d1", "list-item-midas-midas_1b0157b280ce7a5e", "list-item-midas-midas_1b0157b280cf9706"]
> #diff new: ["list-item-sap-B67E068B-327F-43F8-9673-7009965460DE", "list-item-sap-329CFEB6-5ABD-427C-A6F7-411CAC8A439E", "list-item-sap-713B77AC-17B9-40A8-8FFB-6F2521513952", "list-item-sap-E88C1F39-A6F3-49C2-A61B-F34082D575B3", "list-item-sap-D7E9CEE4-E0F0-4BB7-8797-2D2E8FFA6A65", "list-item-sap-7EE76514-1B8A-4D94-B828-AE5FA1514294", "list-item-sap-571DC82C-8D10-45E8-89E9-341CD67C35C0", "list-item-sap-98E6056F-8F9D-4BA1-B733-3A3D039D203B", "list-item-sap-71CCF5BF-E766-431A-87AB-F3FB057EB1E8", "list-item-sap-832FB297-82BE-4486-9F32-BE8245615EBA", "list-item-sap-592B8715-1B64-4ACD-90E0-9CEB300826CC", "list-item-sap-B7D8396A-B91B-4964-B703-977EB50E1457", "list-item-sap-688E2242-252A-4F48-896B-83484AE69462", "list-item-midas-midas_1b0157b280cda4d1", "list-item-midas-midas_1b0157b280d8082b", "list-item-midas-midas_1b0157b280ce7a5e", "list-item-midas-midas_1b0157b280cf9706", "list-item-sap-B01F5755-6C9D-473A-88C3-EE388F8321D8", "list-item-sap-FB5209B3-AE33-4408-B8C1-0DEE94373BF3", "list-item-sap-06A1D63A-6EB6-4EB7-99F8-38726FA5CAC2", "list-item-sap-69BF1835-AB35-4D2A-9E6A-ADF548EA097D", "list-item-sap-0C77DF4E-5E10-440A-B4DA-2690C9E1FA9F", "list-item-sap-9175654D-D0ED-4B96-BDF3-37CA6728C68C", "list-item-sap-2E646044-6372-40AB-B462-5AD07896635F", "list-item-sap-E88800F4-1618-4496-8327-A3B6196B66BF", "list-item-sap-A16969AC-9AB0-4A74-B2D6-5101AC37EEBD", "list-item-sap-016A179F-8AE9-49D1-9174-3A0743FD936B", "list-item-sap-A0BB66CB-9031-429E-BB70-00F96B3C0591", "list-item-sap-B6B4AF81-CD1B-4D83-9F6D-96B9CFC60A62", "list-item-sap-0E4842E5-DCE5-45B6-9FAC-C1EE83AD433B", "list-item-sap-FFA324AE-16B9-4954-AF13-1784F7798665", "list-item-sap-CA4DA8C3-D2F0-4E31-8435-0AE18879D5E8", "list-item-sap-8A1A570F-D690-4DDD-9FDA-49ABDAB039CF"]
> #diff: Diff<String>(results: [Render.DiffStep<Swift.String>.delete(0, "list-item-midas-midas_1b0157b280d8082b"), Render.DiffStep<Swift.String>.insert(0, "list-item-sap-B67E068B-327F-43F8-9673-7009965460DE"), Render.DiffStep<Swift.String>.insert(1, "list-item-sap-329CFEB6-5ABD-427C-A6F7-411CAC8A439E"), Render.DiffStep<Swift.String>.insert(2, "list-item-sap-713B77AC-17B9-40A8-8FFB-6F2521513952"), Render.DiffStep<Swift.String>.insert(3, "list-item-sap-E88C1F39-A6F3-49C2-A61B-F34082D575B3"), Render.DiffStep<Swift.String>.insert(4, "list-item-sap-D7E9CEE4-E0F0-4BB7-8797-2D2E8FFA6A65"), Render.DiffStep<Swift.String>.insert(5, "list-item-sap-7EE76514-1B8A-4D94-B828-AE5FA1514294"), Render.DiffStep<Swift.String>.insert(6, "list-item-sap-571DC82C-8D10-45E8-89E9-341CD67C35C0"), Render.DiffStep<Swift.String>.insert(7, "list-item-sap-98E6056F-8F9D-4BA1-B733-3A3D039D203B"), Render.DiffStep<Swift.String>.insert(8, "list-item-sap-71CCF5BF-E766-431A-87AB-F3FB057EB1E8"), Render.DiffStep<Swift.String>.insert(9, "list-item-sap-832FB297-82BE-4486-9F32-BE8245615EBA"), Render.DiffStep<Swift.String>.insert(10, "list-item-sap-592B8715-1B64-4ACD-90E0-9CEB300826CC"), Render.DiffStep<Swift.String>.insert(11, "list-item-sap-B7D8396A-B91B-4964-B703-977EB50E1457"), Render.DiffStep<Swift.String>.insert(12, "list-item-sap-688E2242-252A-4F48-896B-83484AE69462"), Render.DiffStep<Swift.String>.insert(14, "list-item-midas-midas_1b0157b280d8082b"), Render.DiffStep<Swift.String>.insert(17, "list-item-sap-B01F5755-6C9D-473A-88C3-EE388F8321D8"), Render.DiffStep<Swift.String>.insert(18, "list-item-sap-FB5209B3-AE33-4408-B8C1-0DEE94373BF3"), Render.DiffStep<Swift.String>.insert(19, "list-item-sap-06A1D63A-6EB6-4EB7-99F8-38726FA5CAC2"), Render.DiffStep<Swift.String>.insert(20, "list-item-sap-69BF1835-AB35-4D2A-9E6A-ADF548EA097D"), Render.DiffStep<Swift.String>.insert(21, "list-item-sap-0C77DF4E-5E10-440A-B4DA-2690C9E1FA9F"), Render.DiffStep<Swift.String>.insert(22, "list-item-sap-9175654D-D0ED-4B96-BDF3-37CA6728C68C"), Render.DiffStep<Swift.String>.insert(23, "list-item-sap-2E646044-6372-40AB-B462-5AD07896635F"), Render.DiffStep<Swift.String>.insert(24, "list-item-sap-E88800F4-1618-4496-8327-A3B6196B66BF"), Render.DiffStep<Swift.String>.insert(25, "list-item-sap-A16969AC-9AB0-4A74-B2D6-5101AC37EEBD"), Render.DiffStep<Swift.String>.insert(26, "list-item-sap-016A179F-8AE9-49D1-9174-3A0743FD936B"), Render.DiffStep<Swift.String>.insert(27, "list-item-sap-A0BB66CB-9031-429E-BB70-00F96B3C0591"), Render.DiffStep<Swift.String>.insert(28, "list-item-sap-B6B4AF81-CD1B-4D83-9F6D-96B9CFC60A62"), Render.DiffStep<Swift.String>.insert(29, "list-item-sap-0E4842E5-DCE5-45B6-9FAC-C1EE83AD433B"), Render.DiffStep<Swift.String>.insert(30, "list-item-sap-FFA324AE-16B9-4954-AF13-1784F7798665"), Render.DiffStep<Swift.String>.insert(31, "list-item-sap-CA4DA8C3-D2F0-4E31-8435-0AE18879D5E8"), Render.DiffStep<Swift.String>.insert(32, "list-item-sap-8A1A570F-D690-4DDD-9FDA-49ABDAB039CF")])
> 2017-07-18 22:10:24.053920+0200 ApproveIT_dev[538:94338] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.7.47/UITableView.m:1442
> 2017-07-18 22:10:24.054778+0200 ApproveIT_dev[538:94338] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 0 from section 0 which only contains 0 rows before the update'

**Comment by zdnk** [comment]
any update @alexdrone?

**Comment by alexdrone** [comment]
Not yet, I'll be working on this next week - when I intend to ship 5.0 :D

**Comment by zdnk** [comment]
Any new features to be excited about for 5.0 release? :)

**Comment by zdnk** [comment]
Any progress on this one ❓

**Comment by alexdrone** [comment]
Had to change the diff strategy and I'm working on integrating IGListDiff (that is more battle-tested) into the project. Expect updates soon :)

**Comment by zdnk** [comment]
Cool, looking forward

**Comment by zdnk** [comment]
@alexdrone Any progress?

**Comment by jewilhel** [comment]
Seems to have disappeared! :(

**Comment by zdnk** [comment]
So v5 is not around the corner?

**Comment by alexdrone** [comment]
Sorry guys, I'm not disappeared.
With iOS11 launch I had a lot of work to do and only now I am starting to be a bit more free.
So I expect to start working again on Render from this weekend!

**Comment by jewilhel** [comment]
Great to hear! Hope things are going well with you! :)

**Comment by zdnk** [comment]
Cool, really need the update for table diff.

**Comment by zdnk** [comment]
I tried using `IGListDiff` with plain `UITableView` and it works beautifully, I had to use mine solution, because we are releasing soon and I need it ready. Maybe I will look into implementation into Render myself if you are not planning to work on this for the next week?
