### ISSUE TITLE
[Feature Request] Inspector highlights changes in state

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#63]
I was playing around with the new Inspector app that you built. I know this is going to be super helpful for my projects, because we are building very complex component hierarchies.

One Feature that would really be helpful is to see nodes that changed state or were re-rendred, and highlighted in some way to make it obvious which parts of the hierarchy are being updated.

thanks for your consideration, 

Jason W,

**Comment by alexdrone** [comment]
I'm planning to integrate https://github.com/flitbit/diff in the inspector js app to show the changes in the hierarchy - I also think it would be really helpful :D

**Comment by jewilhel** [comment]
Sounds excellent! I'll put it to good use!

**Comment by jewilhel** [comment]
Closed this issue, since you mentioned you had similar plans.
