### ISSUE TITLE
[Question] CollectionNode horizontal scrolling flow layout

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#65]
Hi Alex,
I have another question. I've been working with `CollectionNode` and got it working pretty well displaying a set of cards. I can display them in a grid layout and a vertical scrolling flow layout, but I haven't been able to figure out how to change the layout direction and display them in a horizontal scrolling flow layout like a carousel. Is this possible? I tried quite a few Yoga layout commands but wasn't able to change the flow direction.

Any help would be appreciated!

Jason W.

**Comment by zdnk** [comment]
Don't you have to set this up with `UICollectionViewFlowLayout`?

**Comment by jewilhel** [comment]
Actually, I was using Render's new `CollectionNode` and wondering if it supported horizontal layouts using the Yoga layout engine, or if that's only possible with the classic `UICollectionView` using `UICollectionViewFlowLayout` as you mentioned. There is a difference between the two.

**Comment by zdnk** [comment]
I see. I thought you can actually set the layout for collection view.

**Comment by alexdrone** [comment]
I just pushed some changes in `CollectionNode` - now you can pass a custom collection view layout in the constructor - that would probably help right?

**Comment by jewilhel** [comment]
Oh, yes! That would be very helpful! :)

**Comment by jewilhel** [comment]
I just tried the update, it seems to work great! I finally have control of the layout. Thank you very much!

**Comment by jewilhel** [comment]
The only thing I would still request is to be able to control the clipping on the cells content container or just set `cell.clipsToBounds = false` by default so that it doesn't clip my card shadows and layer transform animations. 👍

**Comment by zdnk** [comment]
It would be wise to have this to false by default for performance reasons?

**Comment by jewilhel** [comment]
Thats a good point!

**Comment by alexdrone** [comment]
Is now default to 'false' on master :)

**Comment by jewilhel** [comment]
Excellent! Works great now! I have clean shadows and animations! Thank you very much!
