### ISSUE TITLE
[Feature Request] React style component Lifecycle hooks

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#66]
I was reading through the React documentation and they talked about adding lifecycle hooks to a class:  https://facebook.github.io/react/docs/state-and-lifecycle.html

with `componentDidMount()`
and `componentWillUnmount()`

These component methods would be very handy in addition to the `willUpdate()` and `didUpdate()` methods already available.

For example, I want to trigger animations when I create and present a component to the screen and also I want to trigger another just before the component is removed.

Thanks for your consideration! :)

**Comment by alexdrone** [comment]
On it :)

**Comment by jewilhel** [comment]
Oh, wow! I'm excited for this. This will make deploying animation so much easier! Thanks you!

**Comment by alexdrone** [comment]
Fixed in 4.9

**Comment by alexdrone** [comment]
See the AbsoluteLayoutExample for an example of the api use.

**Comment by jewilhel** [comment]
Man this is great. Had a look at the example code, looks easy enough. Can't wait to try it out. Thanks so much Alex this is so helpful! 👍

**Comment by jewilhel** [comment]
Hi Alex,
I did some testing of the new method `didMount()` in my components after studying your example in the demo project and discovered that the method doesn't get called in child components that are nested in parent components. Apparently, the method only works if the component is the `Root` node of the `ViewController`. This doesn't seem helpful beyond the base node of my view hierarchy.

Thanks for taking a look at this! - Jason W.

**Comment by alexdrone** [comment]
will take care of it and propagate it to children

**Comment by jewilhel** [comment]
Thanks so much Alex! :)

**Comment by jewilhel** [comment]
I'm also curious if the `WillUnmount()` method is too challenging at this time? :) I know you're super busy, I'm just interested in what you think about that one. If its practical or not. I've been trying to figure out how to implement similar functionality myself! Just haven't come up with good ideas.
