### ISSUE TITLE
iOS 9 compatibility?

### ISSUE THREAD

**Issue by metabren** [alexdrone/Render#70]
Hi Alex,

Firstly thanks again for your fantastic work on this project!

We've been using Render since 2.0 and I see that you've recently dropped support for iOS 9 (see https://github.com/alexdrone/Render/commit/798d1e2b7d143206b66f0b5e055e40b54e35d670).

The app we're building needs to support the iPad 2 and 3, which _cannot_ upgrade to iOS 10. I'd really love to know:

Was the choice to make iOS 10 the minimum deployment target was done knowing that it would alienate those above devices? 

(i.e. did you consider this before deciding the change was necessary, or were you now aware of this?)

I only ask this as:

- If it were done with consideration, then I'll need to fork this for iOS 9 compatibility myself.
- If you weren't aware of this, perhaps I could help you bring this project back to supporting iOS 9?

Either way, do you know what specific features were added that require iOS 10? 

Thanks in advance!

Cheers,
Brendan

**Comment by softknife** [comment]
why not iOS8 ?

**Comment by metabren** [comment]
> why not iOS8 ?

AFAIK, all devices that support iOS 8 also support iOS 9. If it's difficult to achieve iOS 8 compatibility in Render, then I think asking users to upgrade to the latest iOS version possible for their device is an acceptable tradeoff.

The divide between iOS 9 & 10 is greater than between 8 & 9, as it drops support for some devices.

**Comment by softknife** [comment]
@metabren If the project can support iOS9, it may be not so difficult to support iOS8, right?  After all ,as you say, the divide between iOS 8 & 9 is not great.

**Comment by alexdrone** [comment]
iOS8 might be complicated because of the lack of `UITableViewAutomaticDimension`.. so ideally we could ship a subset of the lib on iOS8.
iOS9 support should be trivial - will add it back next week!

**Comment by metabren** [comment]
Awesome, thanks @alexdrone! 👍

**Comment by softknife** [comment]
@alexdrone Thanks!

**Comment by alexdrone** [comment]
iOS9 support is back in Render 4.9.1
