### ISSUE TITLE
UIScrollView node stretches its children

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Render#71]
Hello,
I have discovered yet another issue or maybe I have something wrong with my code.
Lets take this code:
```swift
final class DetailHeaderComponentView: ComponentView<DetailHeaderState> {

    override func render() -> NodeType {
        let iconName = state.iconName
        
        let icon = Node<UIImageView>(reuseIdentifier: "detail-icon", key: "detail-icon") { view, layout, size in
            layout.height = 60
            layout.width = layout.height
            layout.marginRight = Theme.baseSpacing
            
            view.clipsToBounds = true
            view.image = UIImage(named: iconName)
            view.backgroundColor = .black
        }
        
        let titles = Node<UIView>(reuseIdentifier: "detail-titles", key: "detail-titles") { view, layout, size in
            layout.flexDirection = .column
            layout.percent.width = 100%
            layout.flex()
            
            view.backgroundColor = .blue
        }
        
        let title = Node<UILabel>(reuseIdentifier: "detail-title", key: "detail-title") { label, layout, size in
            layout.marginBottom = 4
            
            label.textColor = .white
            label.font = Theme.ListItem.Font.title
            label.text = "Some title"
            
            label.backgroundColor = .green
        }
        
        let subtitle = Node<UILabel>(reuseIdentifier: "detail-subtitle", key: "detail-subtitle") { label, layout, size in
            label.textColor = .white
            label.font = Theme.ListItem.Font.subtitle
            label.text = "some subtitle"
            
            label.backgroundColor = .red
        }
        
        titles.add(children: [title, subtitle])
        
        return Node<UIView>(reuseIdentifier: "detail-header-container", key: "detail-header-container") { view, layout, size in
            layout.width = size.width
            layout.flexDirection = .row
            layout.alignContent = .center
            layout.justifyContent = .center
            layout.padding = Theme.baseSpacing
            layout.flex()
            
            view.backgroundColor = .orange
        }.add(children: [
            icon,
            titles,
        ])
    }
}

final class DetailComponentView: ComponentView<DetailState> {
    
    override func render() -> NodeType {
        let scroll = Node<UIScrollView>(reuseIdentifier: "detail-scroll") { view, layout, size in
            layout.width = size.width
            layout.height = size.height
            
            view.showsHorizontalScrollIndicator = false
            view.backgroundColor = .yellow
        }
        
        scroll.add(children: [
            ComponentNode(DetailHeaderComponentView(), in: self, reuseIdentifier: "header", key: "header", state: state.header),
        ])
        return scroll
    }

}

```

The issue is that the result is that the `detail-titles` node is stretched to full UIScrollView height (displayed on the picture below as blue).
![img_0003](https://user-images.githubusercontent.com/2551911/28829012-cc22fc28-76d2-11e7-8e68-86d8bd85b815.PNG)

When I use it anywhere else it just works. It is broken in UIScrollView only.

**Comment by zdnk** [comment]
After checking out your samples I figured the differnce. Apparently it is caused by calling `layout.flex()` in `detail-header-container`. Is there any explanation?

**Comment by alexdrone** [comment]
Well you don't need to use layout.flex() in your detail-header-container.

**Comment by alexdrone** [comment]
also another tip for your code, you don't need keys for all of your items. :)

**Comment by zdnk** [comment]
> Well you don't need to use layout.flex() in your detail-header-container.

Yes I have got that, but I dont know why, if it is not there, it would behave differently outside of `UIScrollView` node no?

> also another tip for your code, you don't need keys for all of your items. :)

Yep, the idea reuseIdentifiers + keys is still not clear to me. Are they used just in collection types?
Also I have another issue opened here for `TableNode` diff regarding this.

**Comment by alexdrone** [comment]
1) No, layout.flex() is a shorthand for grow and shrink set to 1. so if you just want want your parent to wrap your children, you don't need that :)

2) I'll try to be more clear in the documentation, but as a rule:
 - key: Only needed when you have a heterogeneous collection of stateful children nodes and only required for the root node wrapping the child (or the component if is a component added through `ComponentNode`).
- reuseIdentifier: Only required when your view has a custom `create` closure. In other cases it just improve performance.
