### ISSUE TITLE
How to set layout for nested ComponentNode?

### ISSUE THREAD

**Issue by msafder** [alexdrone/Render#72]
I've recently updated my code so that nested components are now using the new 'ComponentNode' but now it looks like I don't have an layout object that I can set? Is this by design or am I misunderstanding something  fundamental about nested ComponentNode(s)?

snippet from your sample code:
```
ComponentNode(AbsoluteLayoutInnerComponent(), in: self) { component, _ in
        component.rect = rect
        component.scale = 0.9
        component.background = Color.darkerGreen
},
```

Thanks again for such an AWESOME UI library!

**Comment by alexdrone** [comment]
So if you have a component, you should take care of its layout inside its `render` method.
You can expose some layout configurations as properties if you wish though.

**Comment by msafder** [comment]
Thanks! Is there a philosophical reason why wrapping with a 'Node' object justifies returning a 'layout' object whereas wrapping with ComponentNode does not? 

For example:
```
Node<UIView> { (view, layout, size) in
	layout.marginLeft = size.width * 0.5
})
```
as opposed to:
```
ComponentNode(AbsoluteLayoutInnerComponent(), in: self) { component, _ in
        component.rect = rect
        component.scale = 0.9
        component.background = Color.darkerGreen

// cannot set margin now 
//		layout.marginLeft = size.width * 0.5
}
```
Again, just trying to get a better understanding of your library. Cheers!

**Comment by alexdrone** [comment]
So, ideally a Node<T> is the most primitive "block" of your UI - doesn't have prop nor states - it just provides a configuration closure where you can describe the node layout and such.
A component is a higher self-contained abstraction that knows how to configure itself, exposes some props to the outside (ideally few and high level) and possibly has a state.

**Comment by alexdrone** [comment]
All of the concepts are derived from React - I try to really adapt those in a UIKit context

**Comment by zdnk** [comment]
I actually just hit this issue too. I want to have some components ready for reuse as building blocks, but the `ComponentNode` function does not allow me to configure the margins, etc.

**Comment by alexdrone** [comment]
You can expose the margins (for example) as a property in your component -
and use that property to configure your margins in the component's render
method - this is what you'd do in React as well

**Comment by msafder** [comment]
Thanks for the for the "Node is the most primitive "block"" and "A component is a higher self-contained abstraction" explanation. I'm really enjoying using this library and just wanted to make sure I squeeze as much goodness out of it but as intended. Cheers!
