### ISSUE TITLE
[Demo] Scrolling components don't scroll

### ISSUE THREAD

**Issue by ooga** [alexdrone/Render#73]
Hi,

I'm not able to scroll in your sample project. Can you fix it to have a working example.

Thanx

**Comment by alexdrone** [comment]
On device or simulator? What simulator are you using?

**Comment by alexdrone** [comment]
It works for me on the sim (with ios9, 10 and 11)

**Comment by ooga** [comment]
I'm on simulator iPhone 7 - iOS 10.3

**Comment by ooga** [comment]
Ok it works on Render 4.1
I was on an old commit

Sorry
