### ISSUE TITLE
[Bug] Inserting Layer at index 0 affects render order of child components

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#75]
I came across this odd behavior when I tried to insert a gradient layer at index 0 in a component that renders several children like this:

`view.layer.insertSublayer(gradientLayer, at: 0)`

For some reason the first child component is bumped to the last index while the other child components render in the correct order. The parent component is set to render the children with a vertical column layout. I've tried a number of ways to fix this, but nothing seems to work. None of the Yoga settings I tried work either. 

Thanks for taking a look at this if you have time.
-Jason W.

**Comment by alexdrone** [comment]
I'd suggest to have that custom layer in a custom view and then add the view as a children node to the parent.

**Comment by jewilhel** [comment]
I did something to that effect as a work around. Thanks for your suggestion.

**Comment by jewilhel** [comment]
I closed this issue because I found a reasonable workaround.
