### ISSUE TITLE
ComponentTableCell doesn't update when width changes

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Render#76]
Hi,

I have hit an obstacle that I do not know how to rerender the Components in `ComponentTableCell` when using plain `UITableView` on iPad when screen rotates and width changes. I would like to avoid using `reloadData()` it is not animated.

**Comment by alexdrone** [comment]
have you tried `tableView.updateVisibleComponents()` when the orientation changes?

**Comment by zdnk** [comment]
It didnt work. Do you have a recommendation where to call this method?

**Comment by zdnk** [comment]
figured it out - I am using `ComponentTableViewCell` which does not conform to `CellNodeType`
