### ISSUE TITLE
Non-protocol type 'UIView' cannot be used within a protocol composition

### ISSUE THREAD

**Issue by Lipe991** [alexdrone/Render#77]
When I try to compile Render im getting

 /ComponentViewCell.swift:12:66: Non-protocol type 'UIView' cannot be used within a protocol composition 

and
 
ComponentViewCell.swift:109:67: Non-protocol type 'UIView' cannot be used within a protocol composition

xcode : Version 8.3.3 (8E3004b)
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)

**Comment by alexdrone** [comment]
Sorry, this is now fixed on head.
