### ISSUE TITLE
Layout issue when navigation bar is not translucent

### ISSUE THREAD

**Issue by ooga** [alexdrone/Render#80]
![render](https://user-images.githubusercontent.com/3911114/29534014-a8228cc0-86b4-11e7-8d4c-ae3463bd57f7.gif)

To reproduce : 
- Edit `ViewController.swift` on Demo app
- change `vc.navigationController?.navigationBar.isTranslucent` to `false`

It seems to add like a margin top
Did you have any idea ?

**Comment by alexdrone** [comment]
that is because in TableNodeExample:69 the padding-top is hardcoded to 64.

**Comment by ooga** [comment]
Ok but it not seems to be the same for the ScrollView example

**Comment by ooga** [comment]
The issue comes from this line

https://github.com/alexdrone/Render/blob/master/Render/helpers/ComponentController.swift#L40

When I comment it, the Scrollview is correctly placed
I hope it help
