### ISSUE TITLE
UIScrollView contentInset

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Render#82]
Hi,
I have an issue in our project where `UIScrollView` in the root component is getting `contentInset` set to 64. I was setting it manually and somehow another 64 was added to it. I have `automaticallyAdjustsScrollViewInsets` set to `false`.

**Comment by zdnk** [comment]
Also, the behaviour changes based on if the content is scrollable or now (if it is overflowing the visible area of `UIScrollView`)

**Comment by zdnk** [comment]
seems like ios 10 and 11 have also different behaviour

**Comment by alexdrone** [comment]
Will look into it, thank you - Found several discrepancies between iOS10 and iOS11
