### ISSUE TITLE
[Feature Request] Magic Move style component transitions

### ISSUE THREAD

**Issue by jewilhel** [alexdrone/Render#83]
Hi Alex,

I came across this very interesting library called **Hero** that allows developers to create **Keynote** like automatic **Magic Move** like transitions:

**Library:**
https://github.com/lkzhao/Hero

**Examples:**
http://lkzhao.com/2016/12/28/hero.html

I'm not sure what kind of support v5.0 might have for animation if any. But it would be great if Render could automatically animate transitions for any component with the same ID on each Render update in a similar way as the Hero framework does. And it would be even greater to have event hooks when components are added or removed from a component hierarchy so proper present and dismiss animations could properly bring things on and off the screen. Currently this is very difficult to accomplish.

Thanks for your consideration.

Jason W

**Comment by alexdrone** [comment]
Hey.. please check the API I'm building for neutrino.
I'm exposing a `layoutanimator` that automatically animates layouts and you can provide `UIViewPropertyAnimator` for every property you configure in a node.

**Comment by jewilhel** [comment]
That sounds really awesome. I go have a look at the API.
