### ISSUE TITLE
Release 4.9.2 not available via Cocoapod

### ISSUE THREAD

**Issue by ooga** [alexdrone/Render#86]
https://cocoapods.org/pods/Render

**Comment by ngocdaothanh** [comment]
Hi can you please release the latest version 4.9.2 to Cocoapods?

**Comment by ngocdaothanh** [comment]
The `version` in [Render.podspec](https://github.com/alexdrone/Render/blob/master/Render.podspec) is still 4.9.1.

My Podfile has this:

```
pod 'Render', :git => 'https://github.com/alexdrone/Render.git'
```

But when I run `pod install`, it still reports 4.9.1:

```
Analyzing dependencies
Pre-downloading: `Render` from `https://github.com/alexdrone/Render.git`
Downloading dependencies
Installing Render 4.9.1 (was 4.9.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

**Comment by jondwillis** [comment]
In case anyone wants Swift 4 support via Cocoapods in the mean-time:

`pod 'Render', :git => 'https://github.com/alexdrone/Render.git', :tag => '4.9.2'`
