### ISSUE TITLE
Example for setting tableHeaderView?

### ISSUE THREAD

**Issue by msafder** [alexdrone/Render#87]
Hello,

Thanks again for creating such an awesome library! I'm writing to request an example of how/where we should set the "tableHeaderView" property of UITableView based on your demo example for ComponentEmbeddedInCellExampleViewController or even with TableNode? 

[https://github.com/alexdrone/Render/blob/master/samples/Demo/examples/ComponentEmbeddedInCellExample.swift](url)

The part I'm stumbling on is where to put the Render code for the "tableHeaderView" since it's separate from the table cells and not a typical subview?

Surely I'm not the only one that needs to customize the tableHeaderView?

Thanks in advance. -mo #

**Comment by alexdrone** [comment]
have you tried setting the tableviewheader in the configure closure?

**Comment by msafder** [comment]
Is it possible to render a UIView independent of the UIViewController hierarchy?

For example I want to use Render to render the UiTableView and the table header view separately and then set the "tableView.tableHeaderView" in the UIViewController. Or am I totally off the mark? 

thanks in advance -mo

**Comment by alexdrone** [comment]
It's now in the Feed example for Neutrino.
