### ISSUE TITLE
Port Documentation.

### ISSUE THREAD

**Issue by alexdrone** [alexdrone/Render#96]
Ditto.

**Comment by ngocdaothanh** [comment]
Can you write a brief guide how to convert code from using v4 to using v5? Thanks.

**Comment by zdnk** [comment]
I think the thing that is stopping a lot of people using Neutrino is lack of documentation. Even I am not comfortable to update to Neutrino yet.

**Comment by ngocdaothanh** [comment]
Yeah, I'd like to update to v5, but I'm still stuck with v4. A simple guide to update from v4 to v5 will be very helpful.

**Comment by ngocdaothanh** [comment]
Hi, this issue is now closed, but can you comment something about how to port apps using older versions of Render to the latest version? I see that now Render is "SwiftUI inspired".

**Comment by alexdrone** [comment]
Opened a new issue about it :)
