### ISSUE TITLE
Neutrino: table component layout performance

### ISSUE THREAD

**Issue by zdnk** [alexdrone/Render#97]
Hey,
I have checked the examples on running on iPhone X and the table component is still a bit laggy in facebook feed example, maybe the layout is called too many times?

Z.

**Comment by zdnk** [comment]
I changed reconcile time threshold to 0 to see all layout calls. Every time a new UITableView cell should be displayed, the layout is called 2 times for facebook feed.

> UINode<UIView>.reconcile (11.587977) ms.
> UINode<UIView>.reconcile (8.062005) ms.

First time from TableComponent:210:
```swift
    disableImplicitAnimations {
      cell.selectionStyle = cellInfo.selectionStyle
      cell.mount(component: component, width: tableView.bounds.size.width)
    }
```

Second time from TableComponent.swift:230:
```swift
    disableImplicitAnimations {
      node.reconcile(in: prototypeView,
                     size: CGSize(width: tableView.bounds.size.width, height: CGFloat.max),
                     options: [.preventDelegateCallbacks])
    }
```

**Comment by alexdrone** [comment]
Is it the example with the *UITableComponent* or with the VC? 
The node is rendered 2 times - one to determine its height and the second to render the actual cell.

**Comment by zdnk** [comment]
I think both.
Yep I figured the reason, but it is what makes the table view laggy when scrolling. Can it be cached somehow when it is rendered first time?

**Comment by zdnk** [comment]
@alexdrone any update on the issue?

**Comment by alexdrone** [comment]
This is now fixed in favor of a VC implementation - the abstraction is a bit lower but offers more granular perf improvements.
